Call `Session.remove` after each run, to survive DB restart
Without this, we get the following exception for subsequent runs after a
DB restart, indefinitely:

    sqlalchemy.exc.InvalidRequestError: This Session's transaction has
    been rolled back due to a previous exception during flush. To begin
    a new transaction with this Session, first issue Session.rollback().
    Original exception was: (psycopg2.OperationalError) terminating
    connection due to administrator command