[AIRFLOW-1177] Fix Variable.setdefault w/existing JSON
Previously due to a logic error if you attempt to
use
`Variable.setdefault()` with
`deserialize_json=True` and the value
already existed it would die with:

    ...
        my = Variable.setdefault('regions', ['uk'],
deserialize_json=True)
      File "/usr/local/lib/python3.5/site-
packages/airflow/models.py", line 3623, in
setdefault
        return json.loads(obj.val)
    AttributeError: 'str' object has no attribute
'val'

The problem was that the `Variable.get()` call was
returning the value,
not a variable object.

Closes #2540 from ashb/variable-setdefault-json